codecov:
  require_ci_to_pass: false
comment:
  behavior: default
  layout: reach,diff,flags,tree,reach
  show_carryforward_flags: true
coverage:
  precision: 4
  range:
    - 0.0
    - 100.0
  round: up
  status:
    changes: true
    default_rules:
      flag_coverage_not_uploaded_behavior: include
    patch: true
    project: true
github_checks:
  annotations: false
