[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "justuse"
version = "2025.34"
description = "a pure-python alternative to import"
readme = "README.md"
authors = [
    { name = "Anselm Kiefner", email = "justuse-pypi@anselm.kiefner.de" },
]
license = "MIT"
requires-python = ">=3.12"
keywords = [
    "installing",
    "packages",
    "hot reload",
    "auto install",
    "aspect oriented",
    "version checking",
    "functional",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
]
dependencies = [
    "furl>=2.1.3",
    "jinja2",
    "packaging==24.1",
    "pip",
    "pydantic>=2.8.2",
    "requests",
    "wheel",
    "urllib3>=2.2.2",
    "zipp>=3.19.1",
    "GitPython>=3.1.30",
    "zvic>=2025.34",
    "crosshair-tool>=0.0.95",
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
    "pytest-env",
    "hypothesis>=6.23.1",
    "wheel>=0.38",
]

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["justuse"]
include-package-data = true
