[pytest]
addopts = --continue-on-collection-errors --showlocals --color yes --code-highlight yes --verbose --import-mode=append -vv --log-cli-level ERROR --color yes
testpaths = tests
env =
    PYTHONDEBUGMODE=0
norecursedirs = tests/* .git .tox dist build venv src ai_playground beast integration unit