
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-08T08:16:36-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "e40a0b2f152eb98f9ee75f7091f64e3998349492",
 "version": "1.21.0rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
